AnishProject/Models/Documentary.cs
using System;
using System.Collections.Generic;

namespace AnishProject.Models;

public partial class Documentary
{
    public int DocumentaryId { get; set; }

    public string? Title { get; set; }

    public int? GenreId { get; set; }

    public string? Description { get; set; }

    public string? Rating { get; set; }

    public virtual ICollection<DocumentaryReview> DocumentaryReviews { get; } = new List<DocumentaryReview>();

    public virtual Genre? Genre { get; set; }
}

AnishProject/Controllers/DocumentaryController.cs
using Anish_LookAndFeel.Repositories;
using AnishProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AnishProject.Controllers
{
    public class DocumentaryController : Controller
    {
        private readonly IDocumentaryRepository _documentaryRepository;
        private readonly BullflixContext _db;
        public DocumentaryController(IDocumentaryRepository documentaryRepository, BullflixContext db)
        {
            _documentaryRepository = documentaryRepository;
            _db = db;
        }
        public IActionResult ViewAll()
        {
            var documentariesList = _documentaryRepository.DocumentariesList();
            foreach (var documentary in documentariesList)
            {
                documentary.Genre = _db.Genres.SingleOrDefault(x => x.GenreId == documentary.GenreId);
                decimal sum = 0;
                var reviewList = _documentaryRepository.GetDocumentaryReviews(documentary.DocumentaryId);
                foreach (var review in reviewList)
                {
                    sum = sum + (decimal)review.Rating;
                }
                if (reviewList.Any())
                    documentary.Rating = Math.Round((sum / reviewList.Count), 1).ToString();
                else
                    documentary.Rating = 0.ToString();
            }
            return View(documentariesList);
        }
        [HttpGet]
        public IActionResult AddDocumentary()
        {
            ViewBag.Genres = new SelectList(_db.Genres, "GenreId", "GenreName");

            return View();
        }
        [HttpPost]
        public IActionResult AddDocumentary(Documentary id)
        {
            if (ModelState.IsValid)
            {
                Documentary documentary = _documentaryRepository.AddDocumentary(id);
                return RedirectToAction("ViewAll");
            }
            ViewBag.Genres = new SelectList(_db.Genres, "GenreId", "GenreName");
            return View();
        }
        public IActionResult EditDocumentary(int id)
        {
            ViewBag.Genres = new SelectList(_db.Genres, "GenreId", "GenreName");
            Documentary documentary = _documentaryRepository.GetDocumentary(id);
            return View(documentary);
        }
        [HttpPost]
        public IActionResult EditDocumentary(Documentary documentary)
        {
            if (ModelState.IsValid)
            {
                if (_documentaryRepository.Update(documentary))
                {
                    return RedirectToAction("ViewAll");
                }
            }
            ViewBag.Genres = new SelectList(_db.Genres, "GenreId", "GenreName");
            return View();
        }
        public IActionResult Delete(int id)
        {
            if (_documentaryRepository.DeleteDocumentary(id))
            {
                return RedirectToAction("ViewAll");
            }
            TempData["LoginError"] = "Documentary could not be deleted";
            return RedirectToAction("ViewAll", "Docuementary");
        }
        public IActionResult DeleteDocumentaryReview(int id)
        {
            if (_documentaryRepository.DeleteDocumentaryReview(id))
                return RedirectToAction("SeeReviews");
            throw new NotImplementedException();
        }
        public IActionResult SeeReviews(int id)
        {
            var reviws = _documentaryRepository.GetDocumentaryReviews(id);
            foreach (var review in reviws)
            {
                review.Documentary = _db.Documentaries.SingleOrDefault(x => x.DocumentaryId == review.DocumentaryId);
            }
            return View(reviws);
        }
        public IActionResult AddReview()
        {
            ViewBag.Documentaries = new SelectList(_db.Documentaries, "DocumentaryId", "Title");
            return View();
        }
        [HttpPost]
        public IActionResult AddReview(DocumentaryReview id)
        {
            if (ModelState.IsValid)
            {
                DocumentaryReview documentaryReview = _documentaryRepository.AddDocumentaryReview(id);
                return RedirectToAction("SeeReviews", new { id = documentaryReview.DocumentaryId });
            }
            ViewBag.Documentaries = new SelectList(_db.Documentaries, "DocumentaryId", "Title");
            return RedirectToAction("SeeReviews");
        }
    }
}

AnishProject/Views/Documentary/AddDocumentary.cshtml
@model AnishProject.Models.Documentary

@{
    ViewData["Title"] = "AddDocumentary";
    Layout = "_Layout";
}
<head>
    <style>
        .row {
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .btn {
            margin-right: 13rem;
        }
    </style>
</head>
<h2 style="text-align:center">Documentary</h2>
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddDocumentary">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                Genre
                <select asp-for="GenreId" class="form-control" asp-items="ViewBag.Genres"></select>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div style="padding-top:10px" class="form-group">
                <input style="background-color:#66878a;border:hidden" type="submit" value="Create" class="btn btn-primary" />
                <a style="background-color:white;color:#66878a;padding:3.5px" asp-action="ViewAll">Cancel</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AnishProject/Views/Documentary/AddReview.cshtml
@model AnishProject.Models.DocumentaryReview

@{
    ViewData["Title"] = "AddReview";
}
<head>
    <style>
        .row {
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .btn {
            margin-right: 13rem;
        }
    </style>
</head>
<h1 style="text-align:center">AddReview</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddReview">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DocumentaryId" class="control-label"></label>
                <select asp-for="DocumentaryId" class="form-control" asp-items="ViewBag.Documentaries"></select>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input type="number" asp-for="Rating" min="1" max="5" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <input asp-for="Comment" class="form-control" />
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div style="padding-top:10px" class="form-group">
                <input style="background-color:#66878a;border:hidden" type="submit" value="Create" class="btn btn-primary" />
                <a style="background-color:white;color:#66878a;padding:3.5px" asp-action="SeeReviews">Cancel</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AnishProject/Views/Documentary/EditDocumentary.cshtml
@model AnishProject.Models.Documentary

@{
    ViewData["Title"] = "View";
    Layout = "_Layout";
}
<head>
    <style>
        .row {
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .btn {
            margin-right: 14rem;
        }
    </style>
</head>
<h2 style="text-align:center">Documentary</h2>
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditDocumentary">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DocumentaryId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                Genre
                <select asp-for="GenreId" class="form-control" asp-items="ViewBag.Genres"></select>
                <span asp-validation-for="GenreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div style="padding-top:10px" class="form-group">
                <input style="background-color:#66878a;border:hidden" type="submit" value="Save" class="btn btn-primary" />
                <a style="background-color:white;color:#66878a;padding:3.5px" asp-action="ViewAll">Cancel</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AnishProject/Views/Documentary/SeeReviews.cshtml
@model IEnumerable<AnishProject.Models.DocumentaryReview>

@{
    ViewData["Title"] = "SeeReviews";
}
<head>
    <style>
        .table {
            color: white
        }
    </style>
</head>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Documentary)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Documentary.DocumentaryId)
            </td>
                @if (User.IsInRole("Admin"))
                {
                    <td>

                        @Html.ActionLink("Delete", "DeleteDocumentaryReview", new { id = item.ReviewId },
                new { onclick = "return confirm('Are you sure you want to delete?');" })
                    </td>
                }
        </tr>
}
    </tbody>
    <p>
        <input style="background-color:#66878a;border:hidden" type="button" class="button-1" role="button" value="Add Review" onclick="location.href='@Url.Action("AddReview", "Documentary")'" />
    </p>
</table>

AnishProject/Views/Documentary/ViewAll.cshtml
@model IEnumerable<AnishProject.Models.Documentary>

@{
    ViewData["Title"] = "View";
}
<head>
    <style>
        .table {
            color: white
        }
    </style>
</head>
<table class="table">
    <thead>
        <tr>
            <th>
                #
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DocumentaryId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre.GenreName)
                </td>
                @if (User.IsInRole("Admin"))
                {
                    <td>
                        <a asp-action="EditDocumentary" asp-route-id="@item.DocumentaryId">Edit</a> |
                        @Html.ActionLink("Delete", "Delete", new { id = item.DocumentaryId },
                new { onclick = "return confirm('Are you sure you want to delete?');" })|

                        <a asp-action="SeeReviews" asp-route-id="@item.DocumentaryId">See Reviews</a>
                    </td>
                }
                else
                {
                    <td>
                        <a asp-action="SeeReviews" asp-route-id="@item.DocumentaryId">See Reviews</a>
                    </td>
                }
            </tr>
        }
    </tbody>
    <p>
        <input style="background-color:#66878a;border:hidden" type="button" class="button-1" role="button" value="Add Documentary" onclick="location.href='@Url.Action("AddDocumentary", "Documentary")'" />
    </p>
</table>